/** @file Interview 限界上下文公共入口 / Public entry for the Interview bounded context. */

export {
  asUiInterviewPageLimit,
  asUiInterviewScenarioCursor,
  asUiInterviewSessionCursor,
  asUiInterviewTranscriptCursor,
  asUiInterviewType,
  UI_INTERVIEW_PAGE_LIMIT_MAX
} from './domain/models'
export type {
  UiCreateInterviewSessionInput,
  UiInterviewActionPlanItem,
  UiInterviewActionPlanPriority,
  UiInterviewAvatarOutputMode,
  UiInterviewAvatarPreferences,
  UiInterviewCommunicationMetrics,
  UiInterviewDifficulty,
  UiInterviewEndReason,
  UiInterviewEvidenceClaim,
  UiInterviewFallbackTransport,
  UiInterviewIceServer,
  UiInterviewInferenceCostTier,
  UiInterviewInferenceDataRegion,
  UiInterviewInferenceIntent,
  UiInterviewInferenceQualityTier,
  UiInterviewJobTarget,
  UiInterviewKnowledgeSelection,
  UiInterviewKnowledgeSelectionMode,
  UiInterviewKnowledgeVersionId,
  UiInterviewKnowledgeVersionPin,
  UiInterviewMediaPreferences,
  UiInterviewPageLimit,
  UiInterviewRealtimeTransport,
  UiInterviewRecordingConsent,
  UiInterviewReport,
  UiInterviewReportId,
  UiInterviewRichText,
  UiInterviewRubric,
  UiInterviewRubricDimension,
  UiInterviewRubricDimensionId,
  UiInterviewRubricId,
  UiInterviewRubricScore,
  UiInterviewScenario,
  UiInterviewScenarioAuthority,
  UiInterviewScenarioCursor,
  UiInterviewScenarioId,
  UiInterviewScenarioInput,
  UiInterviewScenarioPage,
  UiInterviewScenarioStatus,
  UiInterviewScoreScale,
  UiInterviewSession,
  UiInterviewSessionAuthority,
  UiInterviewSessionCursor,
  UiInterviewSessionId,
  UiInterviewSessionPage,
  UiInterviewSessionStatus,
  UiInterviewTranscriptCursor,
  UiInterviewTranscriptPage,
  UiInterviewTranscriptSegment,
  UiInterviewTranscriptSegmentId,
  UiInterviewTranscriptSpeaker,
  UiInterviewType,
  UiInterviewVersionedReference,
  UiRealtimeConnection,
  UiRealtimeConnectionId
} from './domain/models'
export type {
  UiCreateInterviewReportJobCommand,
  UiCreateInterviewScenarioCommand,
  UiCreateInterviewSessionCommand,
  UiCreateRealtimeConnectionCommand,
  UiEndInterviewSessionCommand,
  UiInterviewReportRead,
  UiInterviewScenarioPageRead,
  UiInterviewScenarioPatch,
  UiInterviewScenarioRead,
  UiInterviewSessionPageRead,
  UiInterviewSessionRead,
  UiInterviewTranscriptPageRead,
  UiUpdateInterviewScenarioCommand
} from './application/requests'
export type {
  InterviewGateway,
  InterviewReportGateway,
  InterviewScenarioGateway,
  InterviewSessionGateway
} from './application/gateway'
export { InterviewHubPage } from './presentation/InterviewHubPage'
export { InterviewRoomPage } from './presentation/InterviewRoomPage'
export { InterviewSetupPage } from './presentation/InterviewSetupPage'
