/** @file resume 限界上下文公共入口 / resume bounded-context public entry. */

export type {
  UiResumeId,
  UiResumeSectionId,
  UiTemplateId,
  UiResumeSectionKind,
  UiResumeItemKind,
  UiResumeItem,
  UiResumeSection,
  UiResumeContactKind,
  UiResumeContact,
  UiResumeProfile,
  UiResumePageSize,
  UiResumePageOrientation,
  UiMeasurementUnit,
  UiMeasurement,
  UiPageInsets,
  UiResumePageIntent,
  UiTypographyIntent,
  UiColorSpace,
  UiColorValue,
  UiPaletteIntent,
  UiSectionLayoutIntent,
  UiTemplateSettingValue,
  UiResumeStyleIntent,
  UiTemplateReference,
  UiResumeDocument,
  UiResumeCard,
  UiTemplateSettingControl,
  UiTemplateSettingValueType,
  UiTemplateSettingChoice,
  UiTemplateSettingDefinition,
  UiTemplateZone,
  UiTemplateCapabilities,
  UiTemplateManifest,
  UiResumeAssistantRole,
  UiResumeAssistantMessage,
  UiResumePreviewState,
  UiResumePreviewModel,
  UiResumePdfArtifact,
  UiResumeRenderJobStatus,
  UiResumeRenderJob,
  UiStartResumePdfRenderInput,
  UiResumeEditorModel,
  UiResumeAssistantChangeId,
  UiResumeProposalId,
  UiResumeProposalStatus,
  UiResumeProposal,
  UiResumeProposalDecisionInput,
  UiResumeAssistantMessageInput,
  UiResumeAssistantTurnResult,
  UiResumeAssistantUndoInput,
  UiResumeAssistantUndoResult,
  UiResumeSectionUpdateInput,
  UiResumeSectionsReorderInput,
  UiResumeSectionDeleteInput,
  UiResumeTemplateSelectionInput,
  UiTemplateSettingsModel
} from './domain/models'
export type { ResumeGateway } from './application/gateway'
export { ResumeEditorPage } from './presentation/ResumeEditorPage'
export { ResumeEntryPage } from './presentation/ResumeEntryPage'
export { TemplateSettingsPage } from './presentation/TemplateSettingsPage'
